const Questions = [
  {
    question: "What is the speed of light?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Describe the process of photosynthesis.",
    subject: "Biology",
    topic: "Botany",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Solve the quadratic equation: ax^2 + bx + c = 0.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Explain Newton's laws of motion.",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Medium",
    marks: 8,
  },
  {
    question: "What is the structure of DNA?",
    subject: "Biology",
    topic: "Genetics",
    difficulty: "Easy",
    marks: 6,
  },
  {
    question: "Find the derivative of f(x) = sin(x).",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "Hard",
    marks: 12,
  },
  {
    question: "Define the concept of entropy in thermodynamics.",
    subject: "Physics",
    topic: "Thermodynamics",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Discuss the classification of living organisms.",
    subject: "Biology",
    topic: "Taxonomy",
    difficulty: "Easy",
    marks: 7,
  },
  {
    question:
      "Solve the system of linear equations: 2x + 3y = 7, 4x - 2y = 10.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Hard",
    marks: 14,
  },
  {
    question: "Explain the wave-particle duality of light.",
    subject: "Physics",
    topic: "Quantum Mechanics",
    difficulty: "Medium",
    marks: 9,
  },
  {
    question: "Compare and contrast mitosis and meiosis.",
    subject: "Biology",
    topic: "Cell Division",
    difficulty: "Easy",
    marks: 6,
  },
  {
    question: "Integrate the function ∫(3x^2 + 2)dx.",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "Hard",
    marks: 13,
  },
  {
    question: "Define electric field and magnetic field.",
    subject: "Physics",
    topic: "Electromagnetism",
    difficulty: "Medium",
    marks: 11,
  },
  {
    question: "Explain the Hardy-Weinberg equilibrium.",
    subject: "Biology",
    topic: "Population Genetics",
    difficulty: "Easy",
    marks: 7,
  },
  {
    question: "Find the limit lim (x → 0) (sin(x)/x).",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "Hard",
    marks: 12,
  },
  {
    question: "Discuss the concept of work in physics.",
    subject: "Physics",
    topic: "Work and Energy",
    difficulty: "Medium",
    marks: 8,
  },
  {
    question: "Describe the structure of a prokaryotic cell.",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Solve the definite integral ∫[0, π] sin(x)dx.",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Explain the concept of gravitational potential energy.",
    subject: "Physics",
    topic: "Gravity",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Discuss the principles of natural selection.",
    subject: "Biology",
    topic: "Evolution",
    difficulty: "Easy",
    marks: 7,
  },
  {
    question: "Find the eigenvalues of the matrix A = | 2  1 | | -1  4 |.",
    subject: "Mathematics",
    topic: "Linear Algebra",
    difficulty: "Hard",
    marks: 14,
  },
  {
    question: "Explain the laws of reflection and refraction.",
    subject: "Physics",
    topic: "Optics",
    difficulty: "Medium",
    marks: 9,
  },
  {
    question: "Describe the process of protein synthesis.",
    subject: "Biology",
    topic: "Genetics",
    difficulty: "Easy",
    marks: 6,
  },
  {
    question: "Evaluate the integral ∫(1/x)dx.",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "Hard",
    marks: 13,
  },
  {
    question: "Define the concept of electric current.",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Medium",
    marks: 11,
  },
  {
    question: "Explain the endocrine system in humans.",
    subject: "Biology",
    topic: "Human Physiology",
    difficulty: "Easy",
    marks: 8,
  },
  {
    question: "Solve the differential equation dy/dx = 2x.",
    subject: "Mathematics",
    topic: "Differential Equations",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Discuss the principles of conservation of energy.",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Explain the structure of a eukaryotic cell.",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 6,
  },
  {
    question: "Evaluate the series Σ(1/n^2) from n = 1 to ∞.",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "Hard",
    marks: 12,
  },
  {
    question: "Define the concept of magnetism.",
    subject: "Physics",
    topic: "Electromagnetism",
    difficulty: "Medium",
    marks: 9,
  },
  {
    question: "Discuss the process of DNA replication.",
    subject: "Biology",
    topic: "Genetics",
    difficulty: "Easy",
    marks: 7,
  },
  {
    question:
      "Solve the system of differential equations dx/dt = y, dy/dt = -x.",
    subject: "Mathematics",
    topic: "Differential Equations",
    difficulty: "Hard",
    marks: 14,
  },
  {
    question: "Explain the laws of thermodynamics.",
    subject: "Physics",
    topic: "Thermodynamics",
    difficulty: "Medium",
    marks: 8,
  },
  {
    question: "Describe the structure of a virus.",
    subject: "Biology",
    topic: "Microbiology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Evaluate the integral ∫e^x dx.",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Discuss the concept of electric resistance.",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Medium",
    marks: 11,
  },
];

export default Questions;
